settlement:
  fileInput: file:c://Users//A676366//Projects//workspace_psa//TalentsBatch//src//test//resources//11cash_in2.csv
  delimiter: ;
  colunms:
        - Account 
        - AccountName 
        - Date 
        - DateValue 
        - InvoiceReference 
        - SettlementId 
        - TransactionId 
        - Order 
        - ProductName 
        - Invoiced 
        - Settled 
        - OriginalAmount 
        - OriginalCurrency 
        - AmountExclTax 
        - TaxAmount 
        - AmountInclTax 
        - Currency 
        - Operation 
        - SettledAmount 
        - SettlementCurrency 
        - OriginalSettlementId 
        - CustomerId 
        - MerchantOperationId 
        - ReportingData1 
        - ReportingData2 
        - ReportingData3 
        - ReportingData4 
        - ReportingData5 
        - CollectMode 
        - Transfer 
        - OperationDate   
  fileOutput:
      - application: 1335549
        path: c://Users//A676366//Projects//workspace_psa//TalentsBatch//target//files//
        name: nemo
        type: csv
        
      - application: 100002
        path: c://Users//A676366//Projects//workspace_psa//TalentsBatch//target//files//
        name: nemo2
        type: csv
        
      - application: 100003
        path: c://Users//A676366//Projects//workspace_psa//TalentsBatch//target//files//
        name:  nemo3
        type: csv 
        
      - application: 100004
        path: c://Users//A676366//Projects//workspace_psa//TalentsBatch//target//files//
        name:  nemo4
        type: csv   